"""Tests for signal spec, catalog, and config alignment."""

import json
import os

import pytest
from eyecatcher import get_root_dir
from eyecatcher.representation import DualCPPNRepresentation
from eyecatcher.signals import catalog, export_for_frontend


def test_neat_config_matches_representation(representation):
    """NEAT config num_inputs/num_outputs match socket signal counts."""
    assert representation.config.genome_config.num_inputs == len(
        representation.visual.inputs
    )
    assert representation.config.genome_config.num_outputs == len(
        representation.visual.outputs
    )
    assert representation.time_config.genome_config.num_inputs == len(
        representation.time.inputs
    )
    assert representation.time_config.genome_config.num_outputs == len(
        representation.time.outputs
    )


def test_signals_export_for_frontend():
    """export_for_frontend returns expected keys (SIGNAL_GROUPS, OUTPUTS, etc.)."""
    rep = DualCPPNRepresentation()
    data = export_for_frontend(rep.signal_spec)
    assert "SIGNAL_GROUPS" in data
    assert "TOGGLEABLE_SIGNALS" in data
    assert "OUTPUTS" in data
    assert "SIGNAL_IDS" in data
    groups = data["SIGNAL_GROUPS"]
    assert any(g.get("label") in ("Spatial", "Temporal", "Interaction") for g in groups)
    assert data["OUTPUTS"] == [
        {"id": "red", "label": "Red"},
        {"id": "green", "label": "Green"},
        {"id": "blue", "label": "Blue"},
    ]
    assert set(data["SIGNAL_IDS"]) >= {
        "activity",
        "mouse_dist",
        "mouse_speed",
        "mouse_x",
        "mouse_y",
    }


def test_frontend_signals_match_backend():
    """Generated config_signals.generated.js matches representation spec export."""
    root = get_root_dir()
    js_path = os.path.join(
        root, "static", "js", "evolution", "config_signals.generated.js"
    )
    if not os.path.isfile(js_path):
        pytest.skip("run make generate-signals to create generated file")
    with open(js_path, encoding="utf-8") as f:
        text = f.read()

    start = text.find("window.EvolutionConfigSignals = ")
    assert start >= 0, "Generated file should assign EvolutionConfigSignals"
    start = text.index("{", start)
    depth = 0
    end = start
    for i, c in enumerate(text[start:], start):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    data = json.loads(text[start : end + 1])

    rep = DualCPPNRepresentation()
    expected = export_for_frontend(rep.signal_spec)
    assert set(data["SIGNAL_IDS"]) == set(expected["SIGNAL_IDS"])
    assert "TOGGLEABLE_SIGNALS" in data
    assert "SIGNAL_GROUPS" in data


def test_generated_signals_file_is_up_to_date():
    """Generated config_signals.generated.js matches current representation spec.

    If this fails, run `make generate-signals` and commit the updated file.
    """
    root = get_root_dir()
    js_path = os.path.join(
        root, "static", "js", "evolution", "config_signals.generated.js"
    )
    if not os.path.isfile(js_path):
        pytest.skip("run make generate-signals to create generated file")

    rep = DualCPPNRepresentation()
    data = export_for_frontend(rep.signal_spec)
    expected_content = (
        "/* Generated by scripts/generate_signal_config.py - do not edit */\n"
        "(function () {\n"
        '    "use strict";\n'
        "    window.EvolutionConfigSignals = " + json.dumps(data, indent=4) + ";\n"
        "})();\n"
    )
    with open(js_path, encoding="utf-8") as f:
        actual_content = f.read()

    assert (
        actual_content == expected_content
    ), "config_signals.generated.js is out of date. Run: make generate-signals"


# ---------------------------------------------------------------
# SignalSpec tests
# ---------------------------------------------------------------


class TestSignalSpec:
    """Tests for SignalSpec and catalog."""

    def test_dual_cppn_has_signal_spec(self, representation):
        """DualCPPN declares a signal_spec with inputs and outputs."""
        spec = representation.signal_spec
        assert len(spec.inputs) > 0
        assert len(spec.outputs) > 0
        ids = spec.input_ids()
        assert "x" in ids
        assert "bias" in ids

    def test_dual_cppn_spec_has_categories(self, representation):
        """DualCPPN signal_spec has spatial and interaction categories."""
        spec = representation.signal_spec
        assert spec.has_category("spatial")
        assert spec.has_category("interaction")

    def test_dual_cppn_spec_has_derived(self, representation):
        """DualCPPN signal_spec has derived inputs (distance)."""
        spec = representation.signal_spec
        assert len(spec.derived_inputs) > 0
        assert spec.derived_inputs[0].id == "distance"

    def test_conway_has_interaction_signals(self):
        """Conway representation declares interaction signals."""
        from eyecatcher.representation.ca import ConwayRepresentation

        ca = ConwayRepresentation()
        spec = ca.signal_spec
        assert spec.has_signal("mouse_x")
        assert spec.has_signal("mouse_y")
        assert spec.has_category("interaction")

    def test_conway_spec_no_outputs(self):
        """Conway representation currently declares no output signals."""
        from eyecatcher.representation.ca import ConwayRepresentation

        ca = ConwayRepresentation()
        assert len(ca.signal_spec.outputs) == 0

    def test_catalog_presets_consistent(self):
        """Catalog convenience presets have expected lengths and ids."""
        assert len(catalog.DUAL_CPPN_VISUAL_INPUTS) == 10
        assert len(catalog.DUAL_CPPN_TIME_INPUTS) == 5
        ids = [s.id for s in catalog.DUAL_CPPN_VISUAL_INPUTS]
        assert "x" in ids and "y" in ids and "bias" in ids

    def test_export_for_frontend_with_spec(self, representation):
        """export_for_frontend(spec) returns SIGNAL_GROUPS and TOGGLEABLE_SIGNALS."""
        data = export_for_frontend(representation.signal_spec)
        assert "SIGNAL_GROUPS" in data
        assert "TOGGLEABLE_SIGNALS" in data
        assert "SIGNAL_IDS" in data
        groups = data["SIGNAL_GROUPS"]
        assert any(
            g.get("label") in ("Spatial", "Temporal", "Interaction") for g in groups
        )

    def test_signal_spec_has_signal(self):
        """SignalSpec.has_signal works for present and absent signals."""
        from eyecatcher.signals.socket import Socket
        from eyecatcher.signals.spec import Signal, SignalSpec

        sock = Socket("test", inputs=(Signal("a", "A"), Signal("b", "B")))
        spec = SignalSpec(sockets=(sock,), outputs=())
        assert spec.has_signal("a")
        assert not spec.has_signal("c")
