#!/usr/bin/env python3
"""
Generate static/js/substrate/config.generated.js from the Python representation export.

Run from repo root: python scripts/generate_representation_config.py
Or: make generate-representation-config
"""

import json
import os
import sys


def _repo_root() -> str:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(script_dir)


def main() -> None:
    root = _repo_root()
    sys.path.insert(0, os.path.join(root, "src"))

    from eyecatcher.representation.export import export_representations_for_frontend

    data = export_representations_for_frontend()
    out_dir = os.path.join(root, "static", "js", "substrate")
    out_path = os.path.join(out_dir, "config.generated.js")
    os.makedirs(out_dir, exist_ok=True)

    js_content = (
        "/* Generated by scripts/generate_representation_config.py - do not edit */\n"
        "(function () {\n"
        '    "use strict";\n'
        "    window.SubstrateConfig = " + json.dumps(data, indent=4) + ";\n"
        "})();\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
