#!/usr/bin/env python3
"""
Generate config_defaults.generated.js from config/evolution_defaults.json.
Frontend fallbacks for population_size, max_population_size, min_population_size,
crossover_probability. Run from repo root: python scripts/generate_evolution_config.py
Or: make generate-evolution-config
"""

import json
import os
import sys


def _repo_root() -> str:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(script_dir)


def main() -> None:
    root = _repo_root()
    path = os.path.join(root, "config", "evolution_defaults.json")
    if not os.path.isfile(path):
        print(f"Missing {path}", file=sys.stderr)
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        print("evolution_defaults.json must be a JSON object", file=sys.stderr)
        sys.exit(1)

    # Subset the frontend needs (fallbacks for EvolutionConfig)
    frontend_keys = [
        "population_size",
        "max_population_size",
        "min_population_size",
        "crossover_probability",
    ]
    defaults = {k: data.get(k) for k in frontend_keys}
    for k in frontend_keys:
        if defaults[k] is None:
            print(
                f"Missing or null key in evolution_defaults.json: {k}", file=sys.stderr
            )
            sys.exit(1)

    out_path = os.path.join(
        root, "static", "js", "evolution", "config_defaults.generated.js"
    )
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    js_content = (
        "/* Generated by scripts/generate_evolution_config.py - do not edit */\n"
        "(function () {\n"
        '    "use strict";\n'
        "    window.EvolutionConfigDefaults = " + json.dumps(defaults, indent=4) + ";\n"
        "})();\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
