#!/usr/bin/env python3
"""
Generate evolution_config_signals.generated.js from the Python signal registry
and validate NEAT config num_inputs/num_outputs match the registry.

Run from repo root: python scripts/generate_signal_config.py
Or: make generate-signals
"""

import json
import os
import re
import sys


def _repo_root() -> str:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(script_dir)


def _neat_value(path: str, key: str) -> int | None:
    """Read a single integer value from a NEAT config file."""
    if not os.path.isfile(path):
        return None
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=\s*(\d+)\s*$", re.MULTILINE)
    with open(path, encoding="utf-8") as f:
        m = pattern.search(f.read())
    return int(m.group(1)) if m else None


def validate_neat(root: str, visual_path: str, time_path: str) -> None:
    """Validate NEAT num_inputs/num_outputs match registry. Exit 1 on mismatch."""
    sys.path.insert(0, os.path.join(root, "src"))
    from eyecatcher.signals import (
        TIME_INPUTS,
        TIME_OUTPUTS,
        VISUAL_INPUTS,
        VISUAL_OUTPUTS,
    )

    visual_full = os.path.join(root, visual_path)
    time_full = os.path.join(root, time_path)

    errors = []
    v_in = _neat_value(visual_full, "num_inputs")
    v_out = _neat_value(visual_full, "num_outputs")
    if v_in is not None and v_in != len(VISUAL_INPUTS):
        errors.append(
            f"NEAT config mismatch: num_inputs in {visual_path} is {v_in}, "
            f"registry has {len(VISUAL_INPUTS)}. Update the NEAT file."
        )
    if v_out is not None and v_out != len(VISUAL_OUTPUTS):
        errors.append(
            f"NEAT config mismatch: num_outputs in {visual_path} is {v_out}, "
            f"registry has {len(VISUAL_OUTPUTS)}. Update the NEAT file."
        )

    t_in = _neat_value(time_full, "num_inputs")
    t_out = _neat_value(time_full, "num_outputs")
    if t_in is not None and t_in != len(TIME_INPUTS):
        errors.append(
            f"NEAT config mismatch: num_inputs in {time_path} is {t_in}, "
            f"registry has {len(TIME_INPUTS)}. Update the NEAT file."
        )
    if t_out is not None and t_out != len(TIME_OUTPUTS):
        errors.append(
            f"NEAT config mismatch: num_outputs in {time_path} is {t_out}, "
            f"registry has {len(TIME_OUTPUTS)}. Update the NEAT file."
        )

    if errors:
        for e in errors:
            print(e, file=sys.stderr)
        sys.exit(1)


def main() -> None:
    root = _repo_root()
    sys.path.insert(0, os.path.join(root, "src"))

    from eyecatcher.algorithm import config as evolution_config
    from eyecatcher.signals import export_for_frontend

    # Use NEAT paths from config (respects EXPERIMENT_CONFIG and experiments.json)
    visual_path = evolution_config.NEAT_CONFIG_PATH
    time_path = evolution_config.NEAT_TIME_CONFIG_PATH
    validate_neat(root, visual_path, time_path)

    data = export_for_frontend()
    out_path = os.path.join(
        root, "static", "js", "evolution", "evolution_config_signals.generated.js"
    )
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    # Emit JS that assigns window.EvolutionConfigSignals
    js_content = (
        "/* Generated by scripts/generate_signal_config.py - do not edit */\n"
        "(function () {\n"
        '    "use strict";\n'
        "    window.EvolutionConfigSignals = " + json.dumps(data, indent=4) + ";\n"
        "})();\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
